# Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Set up Takahē
    init: |
      git clone https://github.com/jointakahe/takahe
      cd takahe/
    command: |
      GITPOD_DOMAIN=$(gp url 8000 | sed 's!https://!!')
      sed -i.bak -E "s=(127.0.0.1:8000|example.com)=${GITPOD_DOMAIN}=g" docker/docker-compose.yml
      docker-compose -f docker/docker-compose.yml up

# Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: takahe-web
    description: Publish the port 8000 for the Takahē server
    port: 8000
    onOpen: open-preview
    visibility: public

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
